Improved Windows build compatibility
bitfocus/companion pull request #1509
Opened 2021-03-20 13:13 UTC by astellingwerf

When I ran the build on Windows 10 in the Git Bash console, at some point, it attempted to start a cmd prompt, where it didn't recognize the syntax of setting the variable at the start of the line.

2021-03-20 13:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitfocus/companion?pullRequest=1509) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bitfocus/companion?pullRequest=1509) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitfocus/companion?pullRequest=1509) it.</sub>

2021-03-21 12:26 UTC, Julusian requested changes
Unfortunately, this does not work. If I try running `yarn dist:prepare:win` on a non-windows machine, then I end up with non-windows sharp binaries.

I have pushed a change to master that I think will work for you, please test and let me know https://github.com/bitfocus/companion/commit/85db6be5666c01ae76a3cd8d59c31088fd7b9283

2021-03-21 14:35 UTC, krocheck commented
For the same reason I typically modify the same script locally to be `set npm_config_platform=win32 && set npm_config_arch=x64 && yarn dist:prepare:sharp`.  The alternate change using `cross-env` worked for me.

2021-03-21 18:54 UTC, astellingwerf commented
`cross-env` seems to work for me. I guess we can close this PR with that.

2021-03-21 18:54 UTC, closed without merging