Added Companion Bank Types
bitfocus/companion pull request #1548
Opened 2021-04-05 15:28 UTC by thedist

Added type interfaces for Companion Banks, and updated the `CompanionFeedback` interface as the `callback` function has a 2nd parameter for the feedbacks bank.

2021-04-06 19:04 UTC, Julusian requested changes

2021-04-06 19:04 UTC, Julusian commented on instance_skel_types.d.ts
> +	alignment:
Please make a CompanionBankAlignment type for these to reduce the duplication

2021-04-06 19:04 UTC, Julusian commented on instance_skel_types.d.ts
> +export interface CompanionBankPreset {
I'm not keen on CompanionBankPreset and CompanionBankPNG being separate types, as they are the same thing, but as the preset version wants a lot of the properties to be optional then it becomes a little messy.

I don't expect you to do anything about this right now, I may have a play myself later

2021-04-07 03:52 UTC, thedist commented
Yeah make any edits you need, my reasoning for this PR is that I'm quite extensively rewriting the vMix module in Typescript, and it was giving warnings because some of my feedback callbacks utilize the bank data which is in the 2nd param, but the interface as it currently stands only defines the 1st param.

2021-04-20 16:54 UTC, Julusian commented
I've made some changes and merged this in 529d079c8272b21c09f12ba4bdd9e2cd66da449d.

Thanks for doing the bulk of it :)

2021-04-20 16:54 UTC, closed without merging